# Generated by Django 3.0.3 on 2020-04-06 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.TextField(blank=True, max_length=50)),
                ('lastName', models.TextField(blank=True, max_length=50)),
                ('currentActiveLeague', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
    ]
