# Generated by Django 3.0.3 on 2020-03-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200319_0844'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='currentActiveLeague',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
