# Generated by Django 3.0.3 on 2020-03-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_gamechoice_league'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentActiveLeague',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
    ]
