# Generated by Django 3.0.3 on 2020-02-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='league',
        ),
    ]
