# Generated by Django 3.0.3 on 2020-04-06 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeScore', models.TextField(blank=True, max_length=10)),
                ('awayScore', models.TextField(blank=True, max_length=10)),
                ('location', models.TextField(blank=True, max_length=20)),
                ('dateTime', models.DateTimeField(null=True)),
                ('pickLocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('name', models.TextField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(default='', max_length=100)),
                ('isPublic', models.BooleanField(default='False')),
                ('admin', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.TextField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('currentActiveWeek', models.TextField(default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picksLocked', models.BooleanField(default=False)),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.TextField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=500)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(through='league.LeagueMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctFlag', models.BooleanField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Week')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='favorite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='league.GameChoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Week'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='league.Team'),
        ),
        migrations.CreateModel(
            name='LeagueMembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name',)},
        ),
    ]
