# Generated by Django 3.0.3 on 2020-02-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Week'),
        ),
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AlterField(
            model_name='week',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
    ]
