# Generated by Django 3.0.3 on 2020-03-24 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number',
        ),
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
        migrations.RemoveField(
            model_name='week',
            name='number',
        ),
        migrations.AddField(
            model_name='game',
            name='awayCity',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='awayScore',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeCity',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='homeScore',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='pickLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='admin',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='league',
            name='isPublic',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='leaguemembership',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='currentActiveWeek',
            field=models.TextField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='week',
            name='picksLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='leaguemembership',
            unique_together={('user', 'league')},
        ),
        migrations.CreateModel(
            name='LeagueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.TextField(blank=True, max_length=50)),
                ('correctFlag', models.BooleanField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Week')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='league.GameChoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeagueMembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
    ]
