# Generated by Django 3.0.3 on 2020-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='favorite',
        ),
        migrations.AddField(
            model_name='game',
            name='awaySpread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='homeSpread',
            field=models.IntegerField(default=0),
        ),
    ]
