# Generated by Django 3.0.3 on 2020-03-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number',
        ),
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
        migrations.RemoveField(
            model_name='week',
            name='number',
        ),
        migrations.AddField(
            model_name='game',
            name='awayCity',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='awayScore',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='homeCity',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='homeScore',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.TextField(blank=True, max_length=50)),
                ('correctFlag', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='league.GameChoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
