# Generated by Django 3.0.3 on 2020-02-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200228_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
    ]
