# Generated by Django 3.0.3 on 2020-03-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200303_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechoice',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
    ]
