# Generated by Django 3.0.3 on 2020-03-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200320_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguemembershiprequest',
            unique_together=set(),
        ),
    ]
