# Generated by Django 3.0.3 on 2020-03-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200302_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
