# Generated by Django 3.0.3 on 2020-03-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_gamechoice_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='currentActiveWeek',
            field=models.TextField(default='1', max_length=100),
        ),
    ]
