# Generated by Django 3.0.3 on 2020-03-20 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0003_auto_20200320_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguemembershiprequest',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguemessage',
            unique_together=set(),
        ),
    ]
