# Generated by Django 3.0.3 on 2020-03-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_season_currentactiveweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechoice',
            name='week',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Week'),
        ),
    ]
