# Generated by Django 3.0.3 on 2020-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_gamechoice_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemembership',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
