# Generated by Django 3.0.3 on 2020-03-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_leaguemembership_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechoice',
            name='correctFlag',
            field=models.BooleanField(default=None),
        ),
    ]
