# Generated by Django 3.0.3 on 2020-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20200310_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='picksLocked',
            field=models.BooleanField(default=False),
        ),
    ]
