# Generated by Django 3.0.3 on 2020-02-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key='true', serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
